### ISSUE TITLE
Cannot find zipfile directory

### ISSUE THREAD

**Issue by vshesh** [jiupinjia/stylized-neural-painting#58]
Hi,

Thanks for the great work! 

Was trying to run the model using your demo colab notebook. I get stuck on the part where I need to download and unzip the checkpoint file. The unzip command gives: 

```
Archive:  checkpoints_G_oilpaintbrush.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of checkpoints_G_oilpaintbrush.zip or
        checkpoints_G_oilpaintbrush.zip.zip, and cannot find checkpoints_G_oilpaintbrush.zip.ZIP, period.
```

Any idea how I can fix this? I tried wget for the same file and no luck there either.

**Comment by jiupinjia** [comment]
Hi @vshesh, Thanks for your feedback. Now it is fixed.

**Comment by vshesh** [comment]
thanks! 
it works for the main renderers, but I still get the same error for the lightweight renderers
(just copied id from the gdrive link and tried to download - same cannot find zip file error persists. Your links work though so maybe I just didn't do something right)

```
file_id = '1FoclmDOL6d1UT12-aCDwYMcXQKSK6IWA'
file_name = './checkpoints_G_watercolor_light.zip'

!gdown --id {file_id}
!unzip {file_name}
```
